version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s %(name)s [%(levelname)s]: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  full_file:
    filename: full.log
    class: logging.FileHandler
    formatter: standard

root:
 level: INFO
 handlers: [full_file]
