name: dpl-neps-ucb-max  # name of yaml
mf: True
sh_based: False
run_function:
  _target_: pfns_hpo.run.run_neps

searcher_init:
  algorithm: mf_ei_bo
searcher_kwargs:
  # _partial_: true  # To not instantiate the class directly as required by neps
  # _target_: neps.optimizers.multi_fidelity.dyhpo.MFEIBO
  acquisition: MF-UCB-max
  acquisition_args: null
  acquisition_sampler: freeze-thaw
  acquisition_sampler_args: null
  surrogate_model: dpl
  step_size: 1  # TODO: set through benchmark input
  surrogate_model_args:
    checkpointing: true
    root_directory: neps_root_directory
    refine_epochs: 20
    default_model_config: # Config for neural networks
      nr_units: 128
      nr_layers: 2
      use_learning_curve: false
      kernel_size: 3
      nr_filters: 4
      nr_cnn_layers: 2
    surrogate_model_fit_args:
      nr_epochs: 250
      batch_size: 64
      early_stopping: false
      early_stopping_patience: 10
      no_improvement_patience: null
      padding_type: zero
      optimizer_args:
        lr: 0.001
  initial_design_fraction: null  # can be null if `initial_design_budget` is set
  initial_design_size: 1  # cannot be None
  initial_design_budget: 1  # set through internal logic if None
