name: mf_ei_bo  # name of yaml
mf: True
sh_based: False
run_function:
  _target_: pfns_hpo.run.run_neps

searcher_init:
  algorithm: mf_ei_bo
searcher_kwargs:
  # _partial_: false  # To not instantiate the class directly as required by neps
  # _target_: neps.optimizers.multi_fidelity.dyhpo.MFEIBO
  acquisition: MFEI
  acquisition_args: null
  acquisition_sampler: freeze-thaw
  acquisition_sampler_args: null
  surrogate_model: gp
  initial_design_fraction: null  # can be null if `initial_design_budget` is set
  initial_design_size: 3  # cannot be None
  initial_design_budget: 3  # set through internal logic if None
