name: pfn-bopfn-broken-5M-ei-max # name of yaml
mf: True
sh_based: False
run_function:
  _target_: pfns_hpo.run.run_neps

searcher_init:
  algorithm: mf_ei_bo
searcher_kwargs:
  acquisition: MFEI-max
  acquisition_args: null
  acquisition_sampler: freeze-thaw
  acquisition_sampler_args: null
  surrogate_model: pfn
  surrogate_model_args:
    model_name: bopfn_broken_1000curves_10params_5M
    checkpointing: true
    root_directory: neps_root_directory
  initial_design_fraction: null  # can be null if `initial_design_budget` is set
  initial_design_size: 1  # cannot be None
  initial_design_budget: 1  # set through internal logic if None
