name: jahs_fashion_mnist
api:
  name: jahs
  task_id: FashionMNIST
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: null
  _target_: mfpbench.get
  step_size: 3
  seed: ${seed}
  preload: true
