name: lcbench-168330-balanced
api:
  name: lcbench
  prior: null
  datadir: ${hydra:runtime.cwd}/data/yahpo-gym-data
  task_id: '168330'
  _target_: mfpbench.get
  step_size: 2
  seed: ${seed}
  preload: true
  value_metric: val_balanced_accuracy
tabular: false
