api:
  _target_: mfpbench.get
  datadir: ${hydra:runtime.cwd}/data/lcbench-tabular/
  name: lcbench_tabular
  preload: true
  prior: null
  remove_constants: true
  seed: ${seed}
  step_size: 2
  task_id: segment
  value_metric: val_balanced_accuracy
  value_metric_test: test_balanced_accuracy
name: lcbench-tabular-segment-balanced
tabular: true
