api:
  _target_: mfpbench.get
  batch_size: 512
  coarseness: 2
  datadir: ${hydra:runtime.cwd}/data/pd1-tabular/
  dataset: imagenet
  model: resnet
  name: pd1_tabular
  preload: true
  seed: ${seed}
  step_size: 3
name: pd1-tabular-imagenet_resnet_512-2
tabular: true
