api:
  _target_: mfpbench.get
  batch_size: 512
  coarseness: 5
  datadir: ${hydra:runtime.cwd}/data/pd1/
  dataset: imagenet
  model: resnet
  name: pd1
  preload: true
  seed: ${seed}
  step_size: 3
name: pd1-imagenet_resnet_512-5
tabular: false
