api:
  _target_: mfpbench.get
  batch_size: 128
  datadir: ${hydra:runtime.cwd}/data/pd1-tabular/
  dataset: uniref50
  model: transformer
  name: pd1_tabular
  preload: true
  seed: ${seed}
  step_size: 3
name: pd1-tabular-uniref50_transformer_128-1
tabular: true
