api:
  _target_: mfpbench.get
  batch_size: 256
  datadir: ${hydra:runtime.cwd}/data/pd1-tabular/
  dataset: cifar10
  model: wide_resnet
  name: pd1_tabular
  preload: true
  seed: ${seed}
  step_size: 3
name: pd1-tabular-cifar10_wideresnet_256
tabular: true
