api:
  _target_: mfpbench.get
  batch_size: 256
  datadir: ${hydra:runtime.cwd}/data/pd1/
  dataset: svhn_no_extra
  model: wide_resnet
  name: pd1
  preload: true
  seed: ${seed}
  step_size: 3
name: pd1-svhn_wideresnet_256
tabular: false
