api:
  _target_: mfpbench.get
  batch_size: 2048
  datadir: ${hydra:runtime.cwd}/data/pd1-tabular/
  dataset: cifar100
  model: wide_resnet
  name: pd1_tabular
  preload: true
  seed: ${seed}
  step_size: 3
name: pd1-tabular-cifar100_wideresnet_2048
tabular: true
