api:
  _target_: mfpbench.get
  batch_size: 256
  datadir: ${hydra:runtime.cwd}/data/pd1-tabular/
  dataset: fashion_mnist
  model: simple_cnn
  name: pd1_tabular
  preload: true
  seed: ${seed}
  step_size: 3
name: pd1-tabular-fashion_simplecnn_256
tabular: true
