api:
  _target_: mfpbench.get
  batch_size: 64
  coarseness: 10
  datadir: ${hydra:runtime.cwd}/data/pd1-tabular/
  dataset: translate_wmt
  model: xformer_translate
  name: pd1_tabular
  preload: true
  seed: ${seed}
  step_size: 3
name: pd1-tabular-translate_xformertranslate_64-10
tabular: true
