api:
  _target_: mfpbench.get
  datadir: ${hydra:runtime.cwd}/data/taskset-tabular/
  name: taskset_tabular
  optimizer: adam8p
  preload: true
  seed: ${seed}
  step_size: 3
  task_id: FixedTextRNNClassification_imdb_patch128_LSTM128_bs64
name: taskset-tabular-nlp-2-8p
tabular: true
