lcbench_ids = ['adult', 'airlines', 'albert', 'Amazon_employee_access', 'APSFailure', 'Australian', 'bank-marketing', 'blood-transfusion-service-center', 'car', 'christine', 'cnae-9', 'connect-4', 'covertype', 'credit-g', 'dionis', 'fabert', 'Fashion-MNIST', 'helena', 'higgs', 'jannis', 'jasmine', 'jungle_chess_2pcs_raw_endgame_complete', 'kc1', 'KDDCup09_appetency', 'kr-vs-kp', 'mfeat-factors', 'MiniBooNE', 'nomao', 'numerai28.6', 'phoneme', 'segment', 'shuttle', 'sylvine', 'vehicle', 'volkert']
pd1_ids = [
    {"model": "wide_resnet", "dataset": "cifar10", "batch_size": 256},
    {"model": "wide_resnet", "dataset": "cifar10", "batch_size": 2048},
    {"model": "wide_resnet", "dataset": "cifar100", "batch_size": 256},
    {"model": "wide_resnet", "dataset": "svhn_no_extra", "batch_size": 256},
    {"model": "simple_cnn", "dataset": "fashion_mnist", "batch_size": 256},
    {"model": "simple_cnn", "dataset": "fashion_mnist", "batch_size": 2048},
    {"model": "simple_cnn", "dataset": "mnist", "batch_size": 256},
    {"model": "simple_cnn", "dataset": "mnist", "batch_size": 2048},
    {"model": "resnet", "dataset": "imagenet", "batch_size": 256, "coarseness": 1},
    {"model": "resnet", "dataset": "imagenet", "batch_size": 256, "coarseness": 2},
    {"model": "resnet", "dataset": "imagenet", "batch_size": 256, "coarseness": 5},
    {"model": "resnet", "dataset": "imagenet", "batch_size": 256, "coarseness": 10},
    {"model": "resnet", "dataset": "imagenet", "batch_size": 512, "coarseness": 1},
    {"model": "resnet", "dataset": "imagenet", "batch_size": 512, "coarseness": 2},
    {"model": "resnet", "dataset": "imagenet", "batch_size": 512, "coarseness": 5},
    {"model": "resnet", "dataset": "imagenet", "batch_size": 512, "coarseness": 10},
    {"model": "resnet", "dataset": "imagenet", "batch_size": 1024, "coarseness": 1},
    {"model": "resnet", "dataset": "imagenet", "batch_size": 1024, "coarseness": 2},
    {"model": "resnet", "dataset": "imagenet", "batch_size": 1024, "coarseness": 5},
    {"model": "transformer", "dataset": "lm1b", "batch_size": 2048},
    {"model": "transformer", "dataset": "uniref50", "batch_size": 128},
    {"model": "xformer_translate", "dataset": "translate_wmt", "batch_size": 64, "coarseness": 1},
    {"model": "xformer_translate", "dataset": "translate_wmt", "batch_size": 64, "coarseness": 2},
    {"model": "xformer_translate", "dataset": "translate_wmt", "batch_size": 64, "coarseness": 5},
    {"model": "xformer_translate", "dataset": "translate_wmt", "batch_size": 64, "coarseness": 10},
]
taskset_ids = [
    {"task_id": "FixedTextRNNClassification_imdb_patch128_LSTM128_avg_bs64", "optimizer": "adam4p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch128_LSTM128_bs64", "optimizer": "adam4p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch128_LSTM128_embed128_bs64", "optimizer": "adam4p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_GRU128_bs128", "optimizer": "adam4p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_GRU64_avg_bs128", "optimizer": "adam4p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_IRNN64_relu_avg_bs128", "optimizer": "adam4p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_IRNN64_relu_last_bs128", "optimizer": "adam4p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_LSTM128_E128_bs128", "optimizer": "adam4p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_LSTM128_bs128", "optimizer": "adam4p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_VRNN128_tanh_bs128", "optimizer": "adam4p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_VRNN64_relu_avg_bs128", "optimizer": "adam4p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_VRNN64_tanh_avg_bs128", "optimizer": "adam4p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch128_LSTM128_avg_bs64", "optimizer": "adam8p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch128_LSTM128_bs64", "optimizer": "adam8p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch128_LSTM128_embed128_bs64", "optimizer": "adam8p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_GRU128_bs128", "optimizer": "adam8p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_GRU64_avg_bs128", "optimizer": "adam8p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_IRNN64_relu_avg_bs128", "optimizer": "adam8p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_IRNN64_relu_last_bs128", "optimizer": "adam8p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_LSTM128_E128_bs128", "optimizer": "adam8p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_LSTM128_bs128", "optimizer": "adam8p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_VRNN128_tanh_bs128", "optimizer": "adam8p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_VRNN64_relu_avg_bs128", "optimizer": "adam8p"},
    {"task_id": "FixedTextRNNClassification_imdb_patch32_VRNN64_tanh_avg_bs128", "optimizer": "adam8p"},
]