name: Checks

on:
  push:
      branches:
          - main
  pull_request: {}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U .[checking]
        pre-commit install
    - name: Run checks
      run: pre-commit run --all-files
